[package]
name = "mithril-client"
version = "0.8.1"
description = "Mithril client library"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
categories = ["cryptography"]
include = ["**/*.rs", "Cargo.toml", "README.md", ".gitignore"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[[test]]
name = "snapshot_list_get_show_download_verify"
path = "tests/snapshot_list_get_show_download_verify.rs"
required-features = ["fs"]

[[test]]
name = "cardano_transaction_proof"
path = "tests/cardano_transaction_proof.rs"
required-features = ["unstable"]

[dependencies]
anyhow = "1.0.79"
async-recursion = "1.0.5"
async-trait = "0.1.77"
chrono = { version = "0.4.33", features = ["serde"] }
flate2 = { version = "1.0.28", optional = true }
flume = { version = "0.11.0", optional = true }
futures = "0.3.30"
reqwest = { version = "0.12.0", features = ["json", "stream"] }
semver = "1.0.21"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
slog = "2.7.0"
strum = { version = "0.26.1", features = ["derive"] }
tar = { version = "0.4.40", optional = true }
thiserror = "1.0.56"
tokio = { version = "1.37.0", features = ["sync"] }
uuid = { version = "1.7.0", features = ["v4"] }
zstd = { version = "0.13.0", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
mithril-common = { path = "../mithril-common", version = "=0.4", features = [
    "fs",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2.12", features = ["js"] }
mithril-common = { path = "../mithril-common", version = "=0.4" }
reqwest = { version = "0.12.0", features = ["json", "stream"] }

[dev-dependencies]
httpmock = "0.7.0"
indicatif = { version = "0.17.7", features = ["tokio"] }
mithril-common = { path = "../mithril-common", version = "=0.4", features = [
    "random",
    "test_tools",
] }
mockall = "0.12.1"
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
tokio = { version = "1.37.0", features = ["macros", "rt"] }
warp = "0.3.6"

[features]
# Include nothing by default
default = []

# Full feature set
full = ["fs"]

# Enable file system releated functionnality, right now that mean ony snapshot download
fs = ["flate2", "flume", "tar", "tokio/rt", "zstd"]
portable = []                                       # deprecated, will be removed soon
unstable = []

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
