name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ main, unstable ]
    steps:
      - name: Fork Sync main (default branch)
        uses: tgymnich/fork-sync@v1.9.0
        with:
          owner: input-output-hk
          base: ${{ matrix.branch }}
          head: ${{ matrix.branch }}
